name: Test AUR tester script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup docker
        run: |
          docker pull archlinux:latest
          
      - name: Build package in docker container
        run: |
          docker run --name AurTesterContainer -v $(pwd):/mnt archlinux:latest bash -c "
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm git base-devel &&
            useradd -m -s /bin/bash builduser &&
            chown -R builduser /mnt &&
            chmod -R u+w /mnt && 
            echo 'builduser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
            su - builduser -c 'cd /mnt && makepkg -si --noconfirm'
          "
          
      - name: Upload built package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: aur-package
          path: ./package-directory/*
          
  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download built package from artifact
        uses: actions/download-artifact@v3
        with:
          name: aur-package
          path: ./downloaded-package

      - name: Setup docker
        run: |
          docker pull archlinux:latest
          
      - name: Test aur-tester
        run: |
          docker run --rm -v $(pwd)/downloaded-package:/mnt archlinux:latest bash -c "
            cd /mnt && ./aur-tester.sh actiona
          "

      - name: Test aur-tester 2
        run: |
          docker run --rm -v $(pwd)/package:/mnt archlinux:latest bash -c "
            cd /mnt && ./aur-tester.sh actiona
          "

