name: Build AUR Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up docker
        run: |
          docker pull archlinux:latest
          
      - name: Build package in docker container
        run: |
          docker run --rm -v $(pwd):/mnt archlinux:latest bash -c "
            pacman -Syu --noconfirm &&
            pacman -S --noconfirm git base-devel &&
            useradd -m -s /bin/bash builduser &&
            echo 'builduser ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&
            su - builduser -c 'sudo cd /mnt && makepkg -si --noconfirm'
          "
